const offers = [
	{
		position: 1,
		sku: "book-1",
		name: "Book 15 contratos",
		plan: "standard",
		attributes: {
			margemReal: 1500,
			margemDePerda: 1400,
			diasParaAprovacao: 10,
			repasse: 90,
			plataformaGratuitaReal: "Sim",
			proftOneGratis: "Sim",
			educaionalEspecialistas: 50,
			salasAoVivoComMentores: "Diária",
			gerenciamentoDeRisco: "Sim",
			acessoriaEspecializada: "Sim",
			suportePsicologico: "Sim",
			cashback: "Sim",
			saqueQuinzenalOuMensal: "Sim",
			cartaoBlack: "Sim",
		},
		pricing: {
			price: "550,40",
			installments: 21,
		},
	},
	{
		position: 2,
		sku: "book-2",
		name: "Book 30 contratos",
		plan: "standard",
		attributes: {
			margemReal: 1500,
			margemDePerda: 1400,
			diasParaAprovacao: 10,
			repasse: 90,
			plataformaGratuitaReal: "Sim",
			proftOneGratis: "Sim",
			educaionalEspecialistas: 50,
			salasAoVivoComMentores: "Diária",
			gerenciamentoDeRisco: "Sim",
			acessoriaEspecializada: "Sim",
			suportePsicologico: "Sim",
			cashback: "Sim",
			saqueQuinzenalOuMensal: "Sim",
			cartaoBlack: "Sim",
		},
		pricing: {
			price: "1550,40",
			installments: 21,
		},
	},
	{
		position: 3,
		sku: "book-3",
		name: "Book 40 contratos",
		plan: "standard",
		attributes: {
			margemReal: 4000,
			margemDePerda: 1400,
			diasParaAprovacao: 10,
			repasse: 90,
			plataformaGratuitaReal: "Sim",
			proftOneGratis: "Sim",
			educaionalEspecialistas: 50,
			salasAoVivoComMentores: "Diária",
			gerenciamentoDeRisco: "Sim",
			acessoriaEspecializada: "Sim",
			suportePsicologico: "Sim",
			cashback: "Sim",
			saqueQuinzenalOuMensal: "Sim",
			cartaoBlack: "Sim",
		},
		pricing: {
			price: "2550,40",
			installments: 21,
		},
	},
];

window.orion.renderTemplate({
	templateId: "offers-template",
	containerId: "offers-container",
	data: { offers: offers },
	callback: () => {
		console.log("Offers template rendered successfully");
	},
});
